name: CI

on:
  push:
    branches:
      - "*"

env:
  PLUGIN_NAME: obsidian-wechat-public-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          npm install
          npm run build